カラーパレットのCSS変数をコアの変数名--wp--preset--color--$slugに合わせる
vektor-inc/vk-color-palette-manager pull request #15
Opened 2022-10-12 05:07 UTC by shimotmk

[#1446](https://github.com/vektor-inc/vk-blocks-pro/issues/1446)
カラーパレットのCSS変数はコアの変数名--wp--preset--color--$slugに合わせないと色が当たらないことがあるので`:root{ --wp--preset--color--' . $color['slug'] . ':' . $color['color'] . '}`を追加しました

### 環境
WordPress 6.1
テーマ:TT2などのブロックテーマ
カスタマイザーでカスタムカラーを設定し画像ブロックで上下左右のboderの色を変えたときに色が変わるか確認お願いします

### 検討.相談
すぐにはリリースしないとしても
--vk-color-custom-1などのCSS変数は廃止して--wp--preset--color--$slugに統一し--vk-color-primaryや--vk-color-primary-darkなどはテーマ側で対応した方が良いかもと思うのですがどうでしょうか？

そうすれば154行目の`$dynamic_css .= ':root{ --' . $color['slug'] . ':' . $color['color'] . '}';`が不要になります

2022-10-13 02:44 UTC, kurudrive commented
@shimotmk 症状確認しました！ありがとうございます！
さらっと確認すると見落としそうな所だと思いますが さすがです！

* 変数名については基本コアの変数に寄せる形で改変できるものは順次改変で賛成です。
* --vk-color-custom-1 とかは僕も消したいと思いますが、ユーザーが使ってる可能性が...0ではないのかちょっとやっかいですね。と、いう事で、古い変数名に新しい変数を割り振るような書き方で1年くらい泳がせてから削除古い変数の行を削除が妥当かなと思いましたがいかがでしょう？

2022-10-13 05:04 UTC, shimotmk commented
@kurudrive 
確認ありがとうございます！
そのようなイメージでした

「古い変数名に新しい変数を割り振るような書き方」とはどういう事でしょうか？
このプルリクで何か修正が必要ですか？

2022-10-13 05:07 UTC, kurudrive requested changes

2022-10-13 05:07 UTC, kurudrive commented on src/VkColorPaletteManager.php
> +				$dynamic_css .= ':root{ --wp--preset--color--' . $color['slug'] . ':' . $color['color'] . '}';
@shimotmk 

> 「古い変数名に新しい変数を割り振るような書き方」とはどういう事でしょうか？

↑ これの事ですー。

2022-10-13 05:08 UTC, kurudrive commented on src/VkColorPaletteManager.php
> +				$dynamic_css .= ':root{ --wp--preset--color--' . $color['slug'] . ':' . $color['color'] . '}';
`$dynamic_css .= ':root{ --' . $color['slug'] . ': var(--wp--preset--color--' . $color['slug'] . ');}';`

2022-10-13 05:15 UTC, shimotmk commented on src/VkColorPaletteManager.php
> +				$dynamic_css .= ':root{ --wp--preset--color--' . $color['slug'] . ':' . $color['color'] . '}';
@kurudrive 
ありがとうございます！
非推奨とわかりやすく良いと思います！

2022-10-13 05:19 UTC, kurudrive approved these changes
@shimotmk 確認ありがとうございます。
僕的には後はバージョン番号だけ上げておいて貰えれば大丈夫ですー！

2022-10-13 05:25 UTC, shimotmk commented
@kurudrive 
了解です！バージョン上げておきました

情報共有も含め一応他の人にも確認お願いしたいのでどなたか確認お願いします

2022-10-19 00:46 UTC, kurudrive commented
- [ ] マージ時に https://github.com/vektor-inc/vk-color-palette-manager/pull/17 の内容が先祖返りしないように防備メモ。こっちのブランチの内容で :root を削除して !important 付きの状態が最新になるはず。

2022-10-20 08:12 UTC, shimotmk commented
#19 で対応した方がわかりやすいと思うのでcloseします🙏

2022-10-20 08:12 UTC, closed without merging