【確認待ち】コアと同様に!importantをつけて詳細度を上げる
vektor-inc/vk-color-palette-manager pull request #17
Opened 2022-10-17 01:45 UTC by shimotmk

Closes #16

NavigationブロックのSubmenuカラーが効かないのでコアと同様に!importantを付けて詳細度を上げました。

Submenuカラーを付けてカスタムカラーの色が反映されるか確認お願いします

2022-10-18 09:50 UTC, kurudrive requested changes

2022-10-18 09:50 UTC, kurudrive commented on src/VkColorPaletteManager.php
> +				$dynamic_css .= ':root .has-' . $color['slug'] . '-border-color { border-color:var(--' . $color['slug'] . ') !important; }';
```suggestion
				$dynamic_css .= '.has-' . $color['slug'] . '-color { color:var(--' . $color['slug'] . ') !important; }';
				$dynamic_css .= '.has-' . $color['slug'] . '-background-color { background-color:var(--' . $color['slug'] . ') !important; }';
				$dynamic_css .= '.has-' . $color['slug'] . '-border-color { border-color:var(--' . $color['slug'] . ') !important; }';
```

@shimotmk !important つけるなら :root は消しちゃっても良いかなと思います。

が、これ

// .has- だけだと負けるので :root は迂闊に消さないように注意

ってかいてあるけど、どのケースで負けるのか書いてないのが良くないですね...。

でも 「:root あり !important 無し」よりも 「:root なし !important あり」の方が強いので、 :root 消しちゃいましょう。上のコメントとともに。

2022-10-19 00:40 UTC, kurudrive approved these changes

2022-10-19 00:42 UTC, kurudrive commented
@shimotmk ありがとうございます。僕としてはOKです。

2022-10-19 00:42 UTC, shimotmk commented on src/VkColorPaletteManager.php
> +				$dynamic_css .= ':root .has-' . $color['slug'] . '-border-color { border-color:var(--' . $color['slug'] . ') !important; }';
@kurudrive 
Good catch
 :rootとコメント削除しておきました！

2022-10-20 08:12 UTC, shimotmk commented
#19 で対応した方がわかりやすいと思うのでcloseします

2022-10-20 08:12 UTC, closed without merging