wp_theme_json_data_defaultを使う方式に変更
vektor-inc/vk-color-palette-manager pull request #19
Opened 2022-10-20 08:11 UTC by shimotmk

#18 #16 #15

WP6.1から追加されるグローバルスタイルフィルター方式の方がサイトエディターなどでも自動でカラーパレットの値を追加してくれるので変更しました。
https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/filters/global-styles-filters.md
これら( #16 #15)二つの変更を含んでいる感がありますが、一緒に作業しないとコンフリクトの対応の方が大変だと思ったので入れています。

・6.0で今まで通りカスタムカラーパレットの値がエディター、フロントで反映されること
・6.1で今まで通りカスタムカラーパレットの値がエディター、フロントで反映されること
・非推奨になる`--vk-color-custom-1`のcss変数を使用することは出来ること

の確認をお願いします。

書き方など他なにか気になる箇所があればご指摘お願いします。

2022-10-22 14:22 UTC, kurudrive requested changes
@shimotmk ありがとうございます。動作は問題ないと思います。
コメントと過去のプルリクに記載の部分だけコメントしました。

2022-10-24 00:34 UTC, shimotmk commented
@kurudrive 
ありがとうございます
良いと思うのでコミットしました！

2022-10-24 00:48 UTC, kurudrive approved these changes

2022-10-28 01:55 UTC, shimotmk commented
確認方法はmappingsを利用すればvendorなどの削除は要らないと思います
例えばvk-block-proとこのリポジトリが同じ階層にある時
vk-block-proの.wp-env.override.jsonに
"mappings":{
		"wp-content/plugins/vk-blocks-pro/vendor/vektor-inc/vk-color-palette-manager": "../vk-color-palette-manager"
	},
を書けばこのリポジトリの内容で上書きされると思います

2022-10-28 05:11 UTC, doshimaf commented
@shimotmk 

> vk-block-proとこのリポジトリが同じ階層にある時
> vk-block-proの.wp-env.override.jsonに
> "mappings":{
> "wp-content/plugins/vk-blocks-pro/vendor/vektor-inc/vk-color-palette-manager": "../vk-color-palette-manager"
> },

こちらの方法で確認しています。

6.0と6.1でカスタムカラーを設定して使用した場合に、同じ出力になれば問題ないという認識でお間違いないでしょうか？

また下記のブランチは、このブランチの変更をvk-blocks-proで確認するためのブランチでしょうか？
https://github.com/vektor-inc/vk-blocks-pro/pull/1463

2022-10-28 05:29 UTC, shimotmk commented
@doshimaf 
このパッケージで追加しているカスタムカラーパレットの出力が同じかどうかです。

---

> また下記のブランチは、このブランチの変更をvk-blocks-proで確認するためのブランチでしょうか？
https://github.com/vektor-inc/vk-blocks-pro/pull/1463

このブランチ https://github.com/vektor-inc/vk-blocks-pro/pull/1463 はこのパッケージをアップデートした後でvk-blocks-proにこのパッケージを入れるためのブランチです。

このプルリク https://github.com/vektor-inc/vk-color-palette-manager/pull/19 が確認出来たらパッケージをアップデートしvk-blocksやLightningに入れる形です。

なのでこのブランチ https://github.com/vektor-inc/vk-color-palette-manager/pull/19 を確認中は関係ないものです

2022-10-28 05:46 UTC, doshimaf commented
@shimotmk 
ありがとうございます！それぞれ承知しました。

カスタムカラーパレットの出力が同じことを確認しました。

2022-10-28 05:46 UTC, doshimaf approved these changes

2022-10-28 05:51 UTC, shimotmk commented
@doshimaf ありがとうございます！

@kurudrive 0.4.0でタグ打っておきますー

2022-10-28 05:51 UTC, merged